# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: cryptofolio
      POSTGRES_PASSWORD: cryptofolio
      POSTGRES_DB: cryptofolio

  cryptofolio-server:
    image: cryptofolio-server
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_USER: cryptofolio
      DB_PASSWORD: cryptofolio
      DB_HOST: db
      DB_NAME: cryptfolio
