# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: cryptofolio
      POSTGRES_PASSWORD: cryptofolio

  cryptofolio-server:
    image: cryptofolio-server
    restart: always
    ports:
      - 8080:8080
