# Use postgres/example user/password credentials
version: '3.1'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  db:
    image: postgres:latest
    restart: always
    networks:
      - internal
    environment:
      POSTGRES_USER: cryptofolio
      POSTGRES_PASSWORD: cryptofolio
      POSTGRES_DB: cryptofolio

  api:
    image: cryptofolio-server:latest
    restart: always
    networks:
      - internal
      - proxy
    labels:
      traefik.enable: "true"
      traefik.backend: "api"
      traefik.frontend.rule: "Host:api.cryptfolio.ovh"
      traefik.docker.network: "proxy"
      traefik.port: "8080"
    environment:
      PORT: "8080"
      DB_USER: cryptofolio
      DB_PASSWORD: cryptofolio
      DB_HOST: db
      DB_NAME: cryptofolio
